### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by lucasliet** [davidkalil10/CoronavirusTracker#1]
- [x] Flat buttons no grafico => Row (Total/Diário   Casos/Óbitos   Diário/Semanal)
- [x] Fazer grafico funcinar com periodo
- [x] Ajustar relogio para 24h
- [x] Aviso landscape
- [x] Ampliar minicards
- [x] Avisar o queridissimo usuário de que a visão em modo paisagem no gráfico é melhor

**Comment by lucasliet** [comment]
@davidkalil10 eu tinha escrito errado as caixas de seleção do markdown, agora da pra você só marcar um ✓ quando finalizar 👍

**Comment by davidkalil10** [comment]
Flat buttons centralizados
Ajustar relogio para 24h
Ajustar filtro data
Ampliar card grafico
Aviso landscape
Ampliar minicards
Avisar o queridissimo usuário de que a visão em modo paisagem no gráfico é melhor

**Comment by davidkalil10** [comment]
Ajustar relogio para 24h
Ampliar card grafico
Aviso landscape (botao para forçar landscape?
Ampliar minicards

**Comment by davidkalil10** [comment]
- [x] Flat buttons no grafico => Row (Total/Diário   Casos/Óbitos   Diário/Semanal)
- [x] Fazer grafico funcinar com periodo
- [x] Ajustar relogio para 24h
- [x] Aviso landscape
- [x] Avisar o queridissimo usuário de que a visão em modo paisagem no gráfico é melhor 
- [x] Ampliar card grafico pra por o titulo junto
- [x] Por icone no app
- [x] Criar build IOS
- [x] Criar artes para a publicação
- [x] Publicar
- [ ] Incluir firebase nos apps
- [ ] Configurar admob no firebase e nos apps
